### ISSUE TITLE
Why not just forEach?

### ISSUE THREAD

**Issue by MarcinMoskala** [Foso/compose-snake-web#5]
https://github.com/Foso/compose-snake-web/blob/01ca6c59492fbf52e3f9b21eced28bf501d6736e/src/commonMain/kotlin/de.jensklingenberg.composesnake/Utils.kt#L3

**Comment by Foso** [comment]
Hi, good question. I got the code from https://github.com/arkivanov/CompoSnake/blob/main/src/main/kotlin/com/arkivanov/composnake/Utils.kt and haven't changed much on the logic part. I think forEach should work fine

**Comment by Foso** [comment]
Just tried it. It's working fine. I removed forEachFast

**Comment by arkivanov** [comment]
`forEachFast` does not allocate the iterator for each iteration, this is the only benefit.

**Comment by MarcinMoskala** [comment]
But is fast only for arrays and array list, and even for them, I don't
really think it is faster than the classic implementation.

czw., 3 cze 2021 o 02:17 Arkadii Ivanov ***@***.***>
napisał(a):

**Comment by arkivanov** [comment]
The time complexity is sti O(N), it just doesn't allocate anything. This is specifically important with nested iteration:

```
a.forEach {
    b.forEach {
        c.forEach {
        }
    }
}
```

Space complexity of the sample above is O(Na * Nb + Na), whereas `forEachFast` would have O(1) space.
